name: Deploy to production
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install requests
      - name: Run deployment
        run: python .github/deploy.py
        env:
          DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
          CPANEL_ENV: production
          CPANEL_TOKEN: ${{ secrets.CPANEL_TOKEN }}
          CPANEL_API_URL: "https://mcft.io:2083"
          CPANEL_API_USER: minecraft
          CPANEL_REPO_PATTERN: "/home/minecraft/repositories/{repo}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_OWNER: ${{ github.repository_owner }}
          GITHUB_COMMIT: ${{ github.sha }}
          GITHUB_RUN_ID: ${{ github.run_id }}
